from enum import Enum

from PySide6.QtGui import QIcon

import tester.AutoLab.icons.resource_icons_rc  # noqa: F401


class IconNames(Enum):
    ADD_GRAY = ":add_gray-24px.svg"
    ADD_GREEN = ":add_green-24px.svg"
    ADD_WHITE = ":add_white-24px.svg"
    ARROW_DOWN_GRAY = ":arrow_down_gray-24px.svg"
    ARROW_DOWN_WHITE = ":arrow_down_white-24px.svg"
    ARROW_LEFT_GRAY = ":arrow_left_gray-24px.svg"
    ARROW_LEFT_WHITE = ":arrow_left_white-24px.svg"
    ARROW_RIGHT_GRAY = ":arrow_right_gray-24px.svg"
    ARROW_RIGHT_WHITE = ":arrow_right_white-24px.svg"
    ARROW_UP_GRAY = ":arrow_up_gray-24px.svg"
    ARROW_UP_WHITE = ":arrow_up_white-24px.svg"
    BUILD_GRAY = ":build_gray-24px.svg"
    BUILD_WHITE = ":build_white-24px.svg"
    CABLE_GRAY = ":cable_gray-24px.svg"
    CABLE_GREEN = ":cable_green-24px.svg"
    CABLE_WHITE = ":cable_white-24px.svg"
    CHECKBOX_GRAY = ":checkbox_gray-24px.svg"
    CHECKBOX_WHITE = ":checkbox_white-24px.svg"
    CHECKBOX_OUTLINE_BLANK_GRAY = ":checkbox_outline_blank_gray-24px.svg"
    CHACKBOX_OUTLINE_BLANK_WHITE = ":checkbox_outline_blank_white-24px.svg"
    CLEAR_GRAY = ":clear_gray-24px.svg"
    CLEAR_RED = ":clear_red-24px.svg"
    CLEAR_WHITE = ":clear_white-24px.svg"
    CONNECT_GREEN = ":connect_green-16px.svg"
    CONNECT_WHITE = ":connect_white-16px.svg"
    CONNECT_PLUGGED_GRAY = ":connect_plugged_gray-16px.svg"
    CONNECT_PLUGGED_WHITE = ":connect_plugged_white-16px.svg"
    CONNECT_UNPLUGGED_GRAY = ":connect_unplugged_gray-16px.svg"
    CONNECT_UNPLUGGED_WHITE = ":connect_unplugged_white-16px.svg"
    CREATE_NEW_FOLDER_GRAY = ":create_new_folder_gray-24px.svg"
    CREATE_NEW_FOLDER_WHITE = ":create_new_folder_white-24px.svg"
    DONE_GRAY = ":done_gray-24px.svg"
    DONW_GREEN = ":done_green-24px.svg"
    DONW_WHITE = ":done_white-24px.svg"
    DYNAMIC_GRAY = ":dynamic_gray-16x.svg"
    DYNAMIC_WHITE = ":dynamic_white-16x.svg"
    DYNAMIC_GROUP_GRAY = ":dynamic_group_gray-16x.svg"
    DYNAMIC_GROUP_WHITE = ":dynamic_group_white-16x.svg"
    ERROR_GRAY = ":error_gray-24px.svg"
    ERROR_RED = ":error_red-24px.svg"
    ERROR_WHITE = ":error_white-24px.svg"
    ERROR_YELLOW = ":error_yellow-24px.svg"
    FOLDER_OPEN_GRAY = ":folder_open_gray-24px.svg"
    FOLDER_OPEN_SKIN = ":folder_open_skin-24px.svg"
    FOLDER_OPEN_WHITE = ":folder_open_white-24px.svg"
    HIGHLIGHT_OFF_GRAY = ":highlight_off_gray-24px.svg"
    HIGHLIGHT_OFF_RED = ":highlight_off_red-24px.svg"
    HIGHTLIGHT_OFF_WHITE = ":highlight_off_white-24px.svg"
    LOOP_GRAY = ":loop_gray-24px.svg"
    LOOP_WHITE = ":loop_white-24px.svg"
    MENU_GRAY = ":menu_gray-24px.svg"
    MENU_WHITE = ":menu_white-24px.svg"
    MOVE_GRAY = ":move_gray-24px.svg"
    MOVE_WHITE = ":move_white-24px.svg"
    NOT_INTERESTED_GRAY = ":not_interested_gray-24px.svg"
    NOT_INTERESTED_RED = ":not_interested_red-24px.svg"
    NOT_INTERESTED_WHITE = ":not_interested_white-24px.svg"
    NOTE_ADD_GRAY = ":note_add_gray-24px.svg"
    NOTE_ADD_WHITE = ":note_add_white-24px.svg"
    OPEN_IN_FULL_GRAY = ":open_in_full_gray-24px.svg"
    OPEN_IN_FULL_WHITE = ":open_in_full_white-24px.svg"
    OPEN_WITH_GRAY = ":open_with_gray-24px.svg"
    OPEN_WITH_WHITE = ":open_with_white-24px.svg"
    PAUSE_CIRCLE_GRAY = ":pause_circle_gray-24px.svg"
    PAUSE_CIRCLE_RED = ":pause_circle_red-24px.svg"
    PAUSE_CIRCLE_WHITE = ":pause_circle_white-24px.svg"
    PLAY_ARROW_GRAY = ":play_arrow_gray-24px.svg"
    PLAY_ARROR_GREEN = ":play_arrow_green-24px.svg"
    PLAY_ARROW_WHITE = ":play_arrow_white-24px.svg"
    PLAY_CIRCLE_GRAY = ":play_circle_gray-24px.svg"
    PLAY_CIRCLE_GREEN = ":play_circle_green-24px.svg"
    PLAY_CIRCLE_WHITE = ":play_circle_white-24px.svg"
    REMOVE_GRAY = ":remove_gray-24px.svg"
    REMOVE_RED = ":remove_red-24px.svg"
    REMOVE_WHITE = ":remove_white-24px.svg"
    SETTINGS_GRAY = ":settings_gray-24px.svg"
    SETTINGS_WHITE = ":settings_white-24px.svg"
    STOP_GRAY = ":stop_gray-24px.svg"
    STOP_RED = ":stop_red-24px.svg"
    STOP_WHITE = ":stop_white-24px.svg"
    THUMB_DOWN_ALT_GRAY = ":thumb_down_alt_gray-24px.svg"
    THUMB_DOWN_ALT_RED = ":thumb_down_alt_red-24px.svg"
    THUMB_DOWN_ALT_WHITE = ":thumb_down_alt_white-24px.svg"
    THUMB_UP_ALT_GRAY = ":thumb_up_alt_gray-24px.svg"
    THUMB_UP_ALT_GREEN = ":thumb_up_alt_green-24px.svg"
    THUMB_UP_ALT_WHITE = ":thumb_up_alt_white-24px.svg"


def create_qicon(name: IconNames) -> QIcon:
    return QIcon(name.value)
